// "Trappole inglesi" — contrastive English-interference drill data
// (plan-speaking.md S5, merging opportunities.md O14 false friends).
//
// Each item is a spot where thinking in English produces wrong (or
// unnatural) Italian. `wrongs` lists the *predicted* interference forms —
// when the learner's answer matches one, the drill shows the targeted `note`
// explaining how Italian frames it instead of a generic ✗. `alt` lists
// other accepted correct answers. This dataset is EN→IT specific, so it is
// course data: a fork for another language pair ships its own or none.

export const TRAP_CATEGORIES = {
  piacere: { it: 'Verbi come piacere', en: 'backwards verbs (piacere-type)' },
  clitic: { it: 'Pronomi prima del verbo', en: 'object pronouns go before the verb' },
  nullsubj: { it: 'Niente soggetto', en: 'no subject pronoun needed' },
  adjpos: { it: "Posizione dell'aggettivo", en: 'adjective after the noun' },
  prepart: { it: 'Preposizioni articolate', en: 'preposition + article fuse' },
  aux: { it: 'Essere o avere?', en: 'auxiliary choice in the past' },
  avere: { it: 'Modi di dire con avere', en: 'states you HAVE, not ARE' },
  falsefriend: { it: 'Falsi amici', en: 'false friends' },
  cera: { it: "C'è / ci sono", en: 'there is / there are' },
  tempo: { it: 'Tempo e durata', en: 'tense and duration' },
  possessivo: { it: 'Possessivi e articoli', en: 'possessives and articles' },
  verbprep: { it: 'Verbi senza preposizione', en: 'no preposition needed' },
};

export const TRAPS = [
  // ── piacere-type verbs: the liked thing is the subject ────────────────────
  { trap: 'piacere', en: 'I like the psalms', it: 'Mi piacciono i salmi',
    wrongs: ['io piaccio i salmi', 'mi piace i salmi'],
    note: 'Italian flips it: the psalms please me. The verb agrees with what is liked — plural salmi → piacciono.' },
  { trap: 'piacere', en: 'I like to pray', it: 'Mi piace pregare',
    wrongs: ['io piaccio pregare', 'mi piacciono pregare'],
    note: 'With an infinitive, piacere is always singular: mi piace pregare.' },
  { trap: 'piacere', en: 'I miss my family', it: 'Mi manca la mia famiglia',
    alt: ['la mia famiglia mi manca'],
    wrongs: ['io manco la mia famiglia', 'mi manco la mia famiglia'],
    note: 'Mancare works like piacere: my family is lacking TO me — mi manca.' },
  { trap: 'piacere', en: 'We like this church', it: 'Ci piace questa chiesa',
    alt: ['questa chiesa ci piace'],
    wrongs: ['noi piacciamo questa chiesa', 'ci piacciono questa chiesa'],
    note: 'The church pleases us: ci piace. Piacciamo would mean WE are pleasing.' },
  { trap: 'piacere', en: 'Do you like the reading?', it: 'Ti piace la lettura?',
    wrongs: ['tu piaci la lettura', 'ti piaci la lettura'],
    note: 'Does the reading please you? — ti piace. Tu piaci means YOU are likeable.' },
  { trap: 'piacere', en: 'I need more time', it: 'Mi serve più tempo',
    alt: ['ho bisogno di più tempo'],
    wrongs: ['io servo più tempo', 'io bisogno più tempo'],
    note: 'Servire works like piacere: more time is needed TO me — mi serve. (Or: ho bisogno di…)' },

  // ── clitic pronouns: before the conjugated verb ────────────────────────────
  { trap: 'clitic', en: 'I see him every Sunday', it: 'Lo vedo ogni domenica',
    wrongs: ['vedo lo ogni domenica', 'vedo lui ogni domenica'],
    note: 'Object pronouns come BEFORE the verb: lo vedo. (Vedo lui only for strong emphasis.)' },
  { trap: 'clitic', en: 'I read it every morning', it: 'Lo leggo ogni mattina',
    alt: ['la leggo ogni mattina'],
    wrongs: ['leggo lo ogni mattina', 'leggo esso ogni mattina'],
    note: '"It" is lo/la placed before the verb — and never esso in speech.' },
  { trap: 'clitic', en: 'She helps me', it: 'Mi aiuta',
    alt: ['lei mi aiuta'],
    wrongs: ['aiuta mi', 'aiuta me', 'lei aiuta me'],
    note: 'Mi goes in front: mi aiuta. Aiuta me only when contrasting (me, not you).' },
  { trap: 'clitic', en: "I'll call you tomorrow", it: 'Ti chiamo domani',
    alt: ['ti chiamerò domani'],
    wrongs: ['chiamo ti domani', 'chiamo te domani'],
    note: 'Ti before the verb — and Italian happily uses the present for near plans: ti chiamo domani.' },
  { trap: 'clitic', en: 'I told him the truth', it: 'Gli ho detto la verità',
    wrongs: ['ho detto lui la verità', 'ho detto lo la verità'],
    note: 'To him = gli, before the auxiliary: gli ho detto.' },
  { trap: 'clitic', en: 'I know (it)', it: 'Lo so',
    wrongs: ['so lo', 'io so esso', 'conosco esso'],
    note: 'Italian needs the object: LO so — literally "it I-know".' },

  // ── null subject: the ending already says who ─────────────────────────────
  { trap: 'nullsubj', en: 'I am tired', it: 'Sono stanco',
    alt: ['sono stanca'],
    wrongs: ['io sono stanco', 'io sono stanca'],
    note: 'Grammatical, but English-flavored: -o on sono already means "I". Io only for emphasis or contrast.' },
  { trap: 'nullsubj', en: 'We read the Bible every day', it: 'Leggiamo la Bibbia ogni giorno',
    wrongs: ['noi leggiamo la bibbia ogni giorno'],
    note: '-iamo already means "we" — drop noi unless you are contrasting (noi sì, loro no).' },
  { trap: 'nullsubj', en: "It's raining", it: 'Piove',
    alt: ['sta piovendo'],
    wrongs: ['esso piove', 'è piovendo'],
    note: 'No dummy "it" in Italian — weather verbs stand alone: piove. ("È piovendo" doesn\'t exist.)' },
  { trap: 'nullsubj', en: 'Are you coming?', it: 'Vieni?',
    alt: ['venite?', 'tu vieni?'],
    wrongs: ['stai venendo?', 'sei venendo?'],
    note: 'Present + question intonation does it all: Vieni? No progressive, no pronoun needed.' },

  // ── adjective position: usually after the noun ────────────────────────────
  { trap: 'adjpos', en: 'a red house', it: 'una casa rossa',
    wrongs: ['una rossa casa'],
    note: 'Descriptive adjectives follow the noun: casa rossa.' },
  { trap: 'adjpos', en: 'an important word', it: 'una parola importante',
    wrongs: ['una importante parola'],
    note: 'Parola importante — after the noun in normal speech.' },
  { trap: 'adjpos', en: 'the Italian language', it: 'la lingua italiana',
    wrongs: ['la italiana lingua', "l'italiana lingua"],
    note: 'Nationality adjectives always follow: la lingua italiana.' },
  { trap: 'adjpos', en: 'a difficult week', it: 'una settimana difficile',
    wrongs: ['una difficile settimana'],
    note: 'Settimana difficile — noun first.' },

  // ── articulated prepositions: they fuse ───────────────────────────────────
  { trap: 'prepart', en: 'in the desert', it: 'Nel deserto',
    wrongs: ['in il deserto'],
    note: 'in + il = nel. Preposition and article fuse into one word.' },
  { trap: 'prepart', en: 'of the Lord', it: 'Del Signore',
    wrongs: ['di il signore'],
    note: 'di + il = del — as in la parola del Signore.' },
  { trap: 'prepart', en: 'to the church', it: 'Alla chiesa',
    wrongs: ['a la chiesa'],
    note: 'a + la = alla.' },
  { trap: 'prepart', en: 'from the mountains', it: 'Dalle montagne',
    wrongs: ['da le montagne'],
    note: 'da + le = dalle.' },
  { trap: 'prepart', en: 'on the table', it: 'Sul tavolo',
    alt: ['sulla tavola'],
    wrongs: ['su il tavolo', 'su la tavola'],
    note: 'su + il = sul.' },

  // ── essere vs avere in the passato prossimo ───────────────────────────────
  { trap: 'aux', en: 'I went to Mass', it: 'Sono andato a Messa',
    alt: ['sono andata a messa'],
    wrongs: ['ho andato a messa'],
    note: 'Motion/change verbs take essere, and the participle agrees: sono andato/andata.' },
  { trap: 'aux', en: 'She was born in Rome', it: 'È nata a Roma',
    wrongs: ['ha nato a roma'],
    note: 'Nascere takes essere: è nata.' },
  { trap: 'aux', en: 'We stayed home', it: 'Siamo rimasti a casa',
    alt: ['siamo rimaste a casa', 'siamo stati a casa'],
    wrongs: ['abbiamo rimasto a casa'],
    note: 'Rimanere takes essere: siamo rimasti.' },
  { trap: 'aux', en: 'I ate too much', it: 'Ho mangiato troppo',
    wrongs: ['sono mangiato troppo'],
    note: 'Transitive verbs take avere: ho mangiato. (Sono mangiato = I was eaten!)' },
  { trap: 'aux', en: 'They arrived late', it: 'Sono arrivati tardi',
    alt: ['sono arrivate tardi'],
    wrongs: ['hanno arrivato tardi'],
    note: 'Arrivare takes essere: sono arrivati.' },

  // ── avere idioms: states you HAVE ─────────────────────────────────────────
  { trap: 'avere', en: 'I am hungry', it: 'Ho fame',
    wrongs: ['sono fame', 'sono affamato'],
    note: 'Italian HAS hunger: ho fame — literally "I have hunger".' },
  { trap: 'avere', en: 'I am thirty years old', it: "Ho trent'anni",
    alt: ['ho trenta anni', 'ho 30 anni'],
    wrongs: ["sono trent'anni", 'sono trenta anni vecchio'],
    note: 'Age is had, not been: ho trent\'anni — "I have thirty years".' },
  { trap: 'avere', en: 'You are right', it: 'Hai ragione',
    wrongs: ['sei ragione', 'sei giusto'],
    note: 'You HAVE reason: hai ragione.' },
  { trap: 'avere', en: 'I am afraid of the dark', it: 'Ho paura del buio',
    wrongs: ['sono paura del buio'],
    note: 'Fear is had: ho paura — "I have fear of the dark".' },
  { trap: 'avere', en: 'I am cold', it: 'Ho freddo',
    wrongs: ['sono freddo'],
    note: 'Ho freddo. (Sono freddo means you are a cold, unfriendly person.)' },

  // ── false friends ─────────────────────────────────────────────────────────
  { trap: 'falsefriend', en: "Actually, I don't agree", it: "In realtà non sono d'accordo",
    alt: ["in realtà, non sono d'accordo", "veramente non sono d'accordo"],
    wrongs: ["attualmente non sono d'accordo"],
    note: 'Attualmente = currently. "Actually" = in realtà.' },
  { trap: 'falsefriend', en: 'My parents live in Milan', it: 'I miei genitori vivono a Milano',
    alt: ['i miei genitori abitano a milano'],
    wrongs: ['i miei parenti vivono a milano', 'i miei parenti abitano a milano'],
    note: 'Parenti = relatives. Parents = genitori.' },
  { trap: 'falsefriend', en: 'a sensible decision', it: 'una decisione sensata',
    alt: ['una decisione ragionevole'],
    wrongs: ['una decisione sensibile'],
    note: 'Sensibile = sensitive. Sensible = sensato/ragionevole.' },
  { trap: 'falsefriend', en: "I'm going to the library", it: 'Vado in biblioteca',
    alt: ['vado alla biblioteca'],
    wrongs: ['vado in libreria', 'vado alla libreria'],
    note: 'Libreria = bookshop. Library = biblioteca.' },
  { trap: 'falsefriend', en: 'The factory is closed', it: 'La fabbrica è chiusa',
    wrongs: ['la fattoria è chiusa'],
    note: 'Fattoria = farm. Factory = fabbrica.' },
  { trap: 'falsefriend', en: 'Eventually he understood', it: 'Alla fine ha capito',
    alt: ['alla fine capì', 'finalmente ha capito'],
    wrongs: ['eventualmente ha capito'],
    note: 'Eventualmente = possibly / if need be. Eventually = alla fine.' },
  { trap: 'falsefriend', en: 'She is well educated', it: 'È molto istruita',
    alt: ['è molto colta', 'è ben istruita', 'è molto istruito'],
    wrongs: ['è molto educata', 'è ben educata'],
    note: 'Educato = polite, well-mannered. Educated = istruito/colto.' },
  { trap: 'falsefriend', en: 'the argument of the sermon', it: "L'argomento del sermone",
    alt: ["il tema del sermone", "l'argomento dell'omelia"],
    wrongs: ['la discussione del sermone'],
    note: 'Argomento = topic/subject — no quarrel implied. A heated argument = una lite/discussione.' },

  // ── there is / there are ──────────────────────────────────────────────────
  { trap: 'cera', en: 'There is a church in the village', it: "C'è una chiesa nel paese",
    wrongs: ['è una chiesa nel paese', 'là è una chiesa nel paese'],
    note: '"There is" = c\'è (ci + è). Not là è.' },
  { trap: 'cera', en: 'There are many saints', it: 'Ci sono molti santi',
    wrongs: ["c'è molti santi", 'sono molti santi'],
    note: 'Plural → ci sono: ci sono molti santi.' },
  { trap: 'cera', en: 'There was a great light', it: "C'era una grande luce",
    alt: ["c'era una luce grande"],
    wrongs: ['era una grande luce', 'là era una grande luce'],
    note: '"There was" = c\'era.' },

  // ── tense & duration ──────────────────────────────────────────────────────
  { trap: 'tempo', en: 'I have been studying Italian for two years', it: 'Studio italiano da due anni',
    alt: ["studio l'italiano da due anni"],
    wrongs: ['ho studiato italiano per due anni', 'sto studiando italiano per due anni'],
    note: 'Still ongoing → PRESENT + da: studio da due anni — "I study since two years".' },
  { trap: 'tempo', en: 'We have lived here since 2020', it: 'Abitiamo qui dal 2020',
    alt: ['viviamo qui dal 2020'],
    wrongs: ['abbiamo vissuto qui dal 2020', 'abbiamo abitato qui dal 2020'],
    note: 'Still living there → present tense: abitiamo qui dal 2020.' },
  { trap: 'tempo', en: 'How long have you been waiting?', it: 'Da quanto tempo aspetti?',
    alt: ['da quanto aspetti?', 'da quanto tempo aspettate?'],
    wrongs: ['quanto tempo hai aspettato?'],
    note: 'Still waiting → present: da quanto tempo aspetti?' },
  { trap: 'tempo', en: "I'm leaving tomorrow", it: 'Parto domani',
    alt: ['me ne vado domani', 'parto per domani'],
    wrongs: ['sto partendo domani', 'sono partendo domani'],
    note: 'Plans use the simple present: parto domani. Sto partendo = right this second.' },

  // ── possessives & articles ────────────────────────────────────────────────
  { trap: 'possessivo', en: 'my mother', it: 'mia madre',
    wrongs: ['la mia madre'],
    note: 'Singular close family drops the article: mia madre, mio padre.' },
  { trap: 'possessivo', en: 'my book', it: 'il mio libro',
    wrongs: ['mio libro'],
    note: 'Everything except singular family keeps the article: IL mio libro.' },
  { trap: 'possessivo', en: 'their house', it: 'la loro casa',
    wrongs: ['loro casa'],
    note: 'Loro always keeps the article — even for family: la loro madre.' },

  // ── verbs that need no preposition ────────────────────────────────────────
  { trap: 'verbprep', en: "I'm looking for the key", it: 'Cerco la chiave',
    alt: ['sto cercando la chiave'],
    wrongs: ['cerco per la chiave', 'sto cercando per la chiave'],
    note: 'Cercare already contains "for": cerco la chiave.' },
  { trap: 'verbprep', en: "I'm waiting for the bus", it: "Aspetto l'autobus",
    alt: ["sto aspettando l'autobus"],
    wrongs: ["aspetto per l'autobus"],
    note: 'Aspettare takes a direct object: aspetto l\'autobus — no "per".' },
  { trap: 'verbprep', en: 'Listen to the word of the Lord', it: 'Ascolta la parola del Signore',
    alt: ['ascoltate la parola del signore'],
    wrongs: ['ascolta alla parola del signore'],
    note: 'Ascoltare takes a direct object: ascolta la parola — no "to".' },
];
