import XCTest
@testable import BibbiaCore

// Parity with the web's clauseSkeleton.js over every passage verse and vocab
// example (fixture generated by ios-native/scripts/generate-fixtures.mjs),
// plus a few readable spot checks so a failure here explains itself.

final class ClauseSkeletonFixtureTests: XCTestCase {
    struct Case: Decodable {
        let text: String
        let roles: String
        let dims: String
        let finiteCount: Int
        let hasParenthetical: Bool
    }

    private static let letter: [ClauseRole: Character] = [
        .plain: ".", .finite: "f", .compound: "c", .participle: "p",
    ]

    func testMatchesWebOnWholeCorpus() throws {
        let cases = try loadFixture("clauseSkeleton", as: [Case].self)
        XCTAssertGreaterThan(cases.count, 400, "fixture should cover every verse and example")
        for c in cases {
            let r = analyzeClauses(c.text)
            let roles = String(r.tokens.map { Self.letter[$0.role]! })
            let dims = String(r.tokens.map { $0.dim ? "1" : "0" })
            XCTAssertEqual(roles, c.roles, "roles: \(c.text)")
            XCTAssertEqual(dims, c.dims, "dims: \(c.text)")
            XCTAssertEqual(r.finiteCount, c.finiteCount, "count: \(c.text)")
            XCTAssertEqual(r.hasParenthetical, c.hasParenthetical, "aside: \(c.text)")
        }
    }
}

final class ClauseSkeletonTests: XCTestCase {
    private func role(_ text: String, _ word: String) -> ClauseRole? {
        analyzeClauses(text).tokens.first { $0.text == word }?.role
    }

    private func dim(_ text: String, _ word: String) -> Bool? {
        analyzeClauses(text).tokens.first { $0.text == word }?.dim
    }

    func testTwoWordVerbCountsOnlyTheHelper() {
        let r = analyzeClauses("Essi furono presi da grande timore,")
        XCTAssertEqual(r.tokens.first { $0.text == "furono" }?.role, .finite)
        XCTAssertEqual(r.tokens.first { $0.text == "presi" }?.role, .compound)
        XCTAssertEqual(r.finiteCount, 1)
    }

    func testBareParticipleIsAShortenedRelative() {
        XCTAssertEqual(role("altro nome dato agli uomini", "dato"), .participle)
        XCTAssertEqual(role("tra i morti", "morti"), .plain)
    }

    func testPostposedPossessiveDoesNotHideTheVerb() {
        XCTAssertEqual(role("il Padre mio è l'agricoltore.", "è"), .finite)
    }

    func testAsideIsDimmedButTheSubjectIsNot() {
        let text = "Tommaso, uno dei Dodici, chiamato Dìdimo, non era con loro."
        XCTAssertEqual(dim(text, "Dodici"), true)
        XCTAssertEqual(dim(text, "chiamato"), true)
        XCTAssertEqual(dim(text, "Tommaso"), false)
    }

    func testCoordinatedListIsNotAnAside() {
        XCTAssertEqual(dim("con tutto il tuo cuore, con tutta la tua anima, con tutta la tua forza.", "anima"), false)
    }

    func testReadingViewSkeletonToggleRoundTrips() {
        var v = ReadingViewState()
        v.toggleSkeleton()
        XCTAssertTrue(v.showsSkeleton)
        XCTAssertEqual(ReadingViewState.decode(v.encoded()), v)
        v.english = .only
        XCTAssertFalse(v.showsSkeleton, "nothing Italian to mark up in the English-only view")
    }
}
