import XCTest
@testable import BibbiaCore

// Cross-validation against the web app's real JS logic. The fixtures in
// Fixtures/*.json are generated by ios-native/scripts/generate-fixtures.mjs,
// which RUNS the web modules (it2ipa.js, answer.js, srs.js, …) and records
// their outputs. Every assertion here proves the Swift port matches the web
// behavior exactly — including on all 259 real vocab cards.

func loadFixture<T: Decodable>(_ name: String, as type: T.Type) throws -> T {
    guard let url = Bundle.module.url(forResource: name, withExtension: "json",
                                      subdirectory: "Fixtures") else {
        throw XCTSkip("fixture \(name).json missing — run node ios-native/scripts/generate-fixtures.mjs")
    }
    let data = try Data(contentsOf: url)
    return try JSONDecoder().decode(T.self, from: data)
}

private var articles: [String] { Course.shared.locale.articles }

final class IPAFixtureTests: XCTestCase {
    func testIPAMatchesWebConverterForEveryCourseWord() throws {
        let expected = try loadFixture("ipa", as: [String: String].self)
        XCTAssertGreaterThan(expected.count, 500, "fixture should cover the whole course vocabulary")
        for (word, ipa) in expected {
            XCTAssertEqual(toIPA(word), ipa, "toIPA(\(word))")
        }
    }
}

final class PronunciationFixtureTests: XCTestCase {
    struct Case: Decodable { let target: String; let recognized: String; let score: Int }

    func testScoresMatchWeb() throws {
        for c in try loadFixture("pronunciation", as: [Case].self) {
            XCTAssertEqual(scorePronunciation(target: c.target, recognized: c.recognized),
                           c.score, "score(\(c.target) | \(c.recognized))")
        }
    }
}

final class NormalizeFixtureTests: XCTestCase {
    struct Case: Decodable { let input: String; let out: String }

    func testNormalizeMatchesWeb() throws {
        for c in try loadFixture("normalize", as: [Case].self) {
            XCTAssertEqual(normalizeText(c.input), c.out, "normalize(\(c.input))")
        }
    }
}

final class AnswerFixtureTests: XCTestCase {
    struct Check: Decodable { let expected: String; let given: String; let ok: Bool }
    struct Canon: Decodable { let input: String; let out: String }

    func testCheckAnswerMatchesWebOnAllVocab() throws {
        for c in try loadFixture("answer", as: [Check].self) {
            XCTAssertEqual(checkAnswer(expected: c.expected, given: c.given, articles: articles),
                           c.ok, "checkAnswer(\(c.expected) | \(c.given))")
        }
    }

    func testCanonicalMatchesWeb() throws {
        for c in try loadFixture("canonical", as: [Canon].self) {
            XCTAssertEqual(canonicalAnswer(c.input, articles: articles), c.out,
                           "canonical(\(c.input))")
        }
    }
}

final class ClozeFixtureTests: XCTestCase {
    struct Result: Decodable { let before: String; let answer: String; let after: String }
    struct Case: Decodable { let term: String; let example: String; let result: Result? }

    func testClozeMatchesWebOnAllVocab() throws {
        let cases = try loadFixture("cloze", as: [Case].self)
        XCTAssertEqual(cases.count, Course.shared.totalVocab)
        for c in cases {
            let got = makeCloze(term: c.term, example: c.example, articles: articles)
            if let want = c.result {
                XCTAssertEqual(got?.before, want.before, "before(\(c.term))")
                XCTAssertEqual(got?.answer, want.answer, "answer(\(c.term))")
                XCTAssertEqual(got?.after, want.after, "after(\(c.term))")
            } else {
                XCTAssertNil(got, "cloze(\(c.term)) should be ineligible")
            }
        }
    }
}

final class SRSFixtureTests: XCTestCase {
    struct Sequence: Decodable {
        let grades: [String]
        let now0: Double
        let stepMs: Double
        let states: [SRSCard]
    }

    func testReviewSequencesMatchWeb() throws {
        for seq in try loadFixture("srs", as: [Sequence].self) {
            var card: SRSCard? = nil
            for (i, g) in seq.grades.enumerated() {
                let grade = SRSGrade(rawValue: g)!
                card = srsReview(card, grade: grade, now: seq.now0 + Double(i) * seq.stepMs)
                XCTAssertEqual(card, seq.states[i], "state \(i) of \(seq.grades)")
            }
        }
    }
}

final class StreakFixtureTests: XCTestCase {
    struct Op: Decodable { let flag: String; let today: String }
    struct Scenario: Decodable {
        let name: String
        let ops: [Op]
        let store: StreakData
        let streakOn: String
        let streak: Int
        let flagsOn: String?
        let flags: TodayFlags?
    }

    func testScenariosMatchWeb() throws {
        for sc in try loadFixture("streak", as: [Scenario].self) {
            var s = StreakData()
            for op in sc.ops {
                s = setFlag(s, flag: StreakFlag(rawValue: op.flag), today: op.today)
            }
            XCTAssertEqual(s, sc.store, "\(sc.name): final store")
            XCTAssertEqual(currentStreak(s, today: sc.streakOn), sc.streak, "\(sc.name): streak")
            if let flagsOn = sc.flagsOn, let flags = sc.flags {
                XCTAssertEqual(todayFlags(s, today: flagsOn), flags, "\(sc.name): flags")
            }
        }
    }
}

final class DictoglossFixtureTests: XCTestCase {
    struct Case: Decodable {
        let original: String
        let attempt: String
        let score: Int
        let originalOk: [Bool]
        let attemptOk: [Bool]
    }

    func testDiffsMatchWeb() throws {
        for c in try loadFixture("dictogloss", as: [Case].self) {
            let d = diffReconstruction(original: c.original, attempt: c.attempt)
            XCTAssertEqual(d.score, c.score, "score(\(c.attempt))")
            XCTAssertEqual(d.original.map(\.ok), c.originalOk, "originalOk(\(c.attempt))")
            XCTAssertEqual(d.attempt.map(\.ok), c.attemptOk, "attemptOk(\(c.attempt))")
        }
    }
}

final class CommonWordsFixtureTests: XCTestCase {
    struct Case: Decodable { let word: String; let gloss: String? }

    func testCommonGlossMatchesWebOnAllCourseText() throws {
        let cases = try loadFixture("commonGloss", as: [Case].self)
        XCTAssertGreaterThan(cases.count, 1000, "fixture should cover the whole course text")
        for c in cases {
            XCTAssertEqual(CommonWords.shared.lookup(c.word), c.gloss, "lookupCommon(\(c.word))")
        }
    }
}
