import Foundation

// Port of src/utils/clauseSkeleton.js — the "Struttura" reading aid for
// hypotactic prose. Classifies each token of a sentence as a conjugated verb
// (`finite`), the participle half of a two-word verb (`compound`), a bare
// participle that works as a shortened relative clause (`participle`), or
// `plain`, and marks comma-delimited asides (`dim`).
//
// The word lists below are copied verbatim from the JS module, and the logic
// follows it function for function. The ClauseSkeleton fixture (generated by
// running the real JS over every passage verse and vocab example) proves the
// two agree token for token, so when a list changes on the web, change it here
// and regenerate the fixtures. The design notes — why each context rule
// exists and what it used to get wrong — live in the JS file.

public enum ClauseRole: String, Codable, Sendable {
    case plain, finite, compound, participle
}

public struct SkeletonToken: Equatable, Sendable {
    public let text: String
    public let isWord: Bool
    public internal(set) var role: ClauseRole
    public internal(set) var dim: Bool

    public init(text: String, isWord: Bool, role: ClauseRole, dim: Bool) {
        self.text = text
        self.isWord = isWord
        self.role = role
        self.dim = dim
    }
}

public struct ClauseAnalysis: Equatable, Sendable {
    public let tokens: [SkeletonToken]
    /// The number of conjugated verbs — the clause count the reader is taught
    /// to look for first.
    public let finiteCount: Int
    public let hasParenthetical: Bool
}

// ── word lists (verbatim from clauseSkeleton.js) ─────────────────────────────

private let aux: Set<String> = Set<String>([
    "sono", "sei", "è", "siamo", "siete", "ero", "eri", "era", "eravamo", "eravate", "erano",
    "fui", "fosti", "fu", "fummo", "foste", "furono", "sarò", "sarai", "sarà", "saremo",
    "sarete", "saranno", "sia", "siano", "fosse", "fossero", "sarei", "sarebbe", "sarebbero",
    "ho", "hai", "ha", "abbiamo", "avete", "hanno", "avevo", "avevi", "aveva", "avevamo",
    "avevate", "avevano", "ebbi", "ebbe", "ebbero", "avrò", "avrà", "avranno", "abbia",
    "abbiano", "avesse", "avessero", "avrei", "avrebbe", "viene", "vengono", "venne",
    "vennero", "veniva", "venivano", "sta", "stanno", "stava", "stavano", "vada", "vadano",
    "andò", "andarono",
])

private let nonfiniteAux: Set<String> = Set<String>([
    "essere", "esser", "avere", "aver", "venire", "essendo", "avendo",
])

private let avere: Set<String> = Set<String>([
    "ho", "hai", "ha", "abbiamo", "avete", "hanno", "avevo", "aveva", "avevano", "ebbe",
    "ebbero", "avrà", "avranno", "abbia", "abbiano", "avesse", "avere", "aver",
])

private let peccatoLike: Set<String> = Set<String>([
    "peccato",
])

private let finiteLexicon: Set<String> = Set<String>([
    "dico", "dici", "dice", "diciamo", "dite", "dicono", "disse", "dissero", "dica", "dicano",
    "dissi", "vidi", "feci", "venni", "presi", "stetti", "faccio", "fai", "fa", "facciamo",
    "fate", "fanno", "fece", "fecero", "faccia", "facciano", "vado", "vai", "va", "andiamo",
    "andate", "vanno", "vada", "vadano", "vedo", "vedi", "vede", "vediamo", "vedete", "vedono",
    "vide", "videro", "veda", "vedano", "so", "sai", "sa", "sappiamo", "sapete", "sanno",
    "seppe", "seppero", "sappia", "posso", "puoi", "può", "possiamo", "potete", "possono",
    "poté", "possa", "possano", "devo", "devi", "deve", "dobbiamo", "dovete", "devono",
    "dovette", "debba", "debbano", "voglio", "vuoi", "vuole", "vogliamo", "volete", "vogliono",
    "volle", "vollero", "voglia", "vogliano", "do", "dà", "diamo", "danno", "diede", "diedero",
    "dette", "dettero", "dia", "diano", "sto", "stai", "stia", "stiano", "stiamo", "stette",
    "rimane", "rimangono", "rimase", "rimasero", "tiene", "tengono", "tenne", "tennero",
    "pone", "pongono", "pose", "posero", "prendo", "prende", "prendono", "prese", "presero",
    "metto", "mette", "mettono", "mise", "misero", "scelgo", "sceglie", "scelgono", "scelse",
    "scelsero", "rispondo", "risponde", "rispondono", "rispose", "risposero", "scrivo",
    "scrive", "scrivono", "scrisse", "scrissero", "leggo", "leggono", "lesse", "lessero",
    "chiede", "chiedono", "chiese", "chiesero", "nasce", "nacque", "nacquero", "cade", "cadde",
    "caddero", "vive", "vivono", "visse", "vissero", "muore", "muoiono", "conosce",
    "conoscono", "conobbe", "conobbero", "cresce", "crebbe", "crebbero", "beve", "bevve",
    "bevvero", "pare", "parve", "parvero", "appare", "apparve", "apparvero", "piace",
    "piacciono", "piacque", "vince", "vinse", "vinsero", "giunge", "giunse", "giunsero",
    "accoglie", "accolse", "accolsero", "coglie", "colse", "colsero", "volge", "volse",
    "volsero", "piange", "pianse", "piansero", "spinge", "spinse", "spinsero", "chiude",
    "chiuse", "chiusero", "avvolge", "avvolse", "avvolsero", "perde", "perse", "persero",
    "corre", "corse", "corsero", "decide", "decise", "decisero", "uccide", "uccise",
    "uccisero", "distrugge", "distrusse", "distrussero", "conduce", "condusse", "condussero",
    "traduce", "tradusse", "scende", "scendi", "scendono", "scese", "scesero", "divide",
    "divise", "divisero", "espone", "espose", "esposero", "concede", "conceda", "concedano",
    "concesse", "concessero", "vale", "valgono", "valga", "possiedo", "possiede", "possiedono",
    "vuol", "suole", "alzati", "àlzati", "goditi", "farà", "farò", "dava", "udii", "caddi",
    "risposi", "impose", "sciolse", "sciolsero", "esalta", "umilia", "discende", "spetta",
    "nutre", "esiste", "splende", "ritengo", "delude", "dimostra", "produce", "abbatte",
    "prega", "parla", "ascolta", "annuncia", "cammina", "perdona", "comanda", "insegna",
    "battezza", "predica", "racconta", "ringrazia", "ama", "amano", "mando", "rendo", "esorto",
    "respira", "respirano", "crede", "credo", "temo", "teme", "segue", "seguo", "vengo",
    "vieni",
]).union(aux).union(nounHomographVerbs)

private let nounHomographVerbs: Set<String> = Set<String>([
    "porta", "portano", "legge", "leggi", "lava", "guida", "opera", "cura", "grida", "canta",
    "ordina", "pesca", "conta", "firma", "posa", "piega", "annuncio",
])

private let prenominal: Set<String> = Set<String>([
    "lieto", "lieta", "buon", "buona", "gran", "grande", "nuovo", "nuova", "santo", "santa",
    "primo", "prima", "ultimo", "ultima", "vero", "vera", "questo", "questa", "questi",
    "queste", "quel", "quello", "quella", "quei", "quegli", "quelle", "ogni", "nessun",
    "nessuna", "alcun", "alcuna", "qualche",
])

private let notFinite: Set<String> = Set<String>([
    "romano", "romani", "cristiano", "italiano", "lontano", "umano", "sovrano", "invano",
    "pagano", "anziano", "piano", "soprano", "oceano", "organo", "platano", "gabbano", "trono",
    "suono", "abbandono", "perdono", "colono", "contorno", "diacono", "diaconi", "sermone",
    "padrono", "anno", "inganno", "affanno", "tiranno", "malanno", "panno", "estremo",
    "supremo", "remo", "però", "perciò", "ciò", "falò", "comò", "lì", "sì", "così", "giù",
    "più", "granai", "ormai", "assai", "guai", "ahimè", "classe", "promesse", "interesse",
    "spesse", "fesse", "parete", "pareti", "monete", "quiete", "profete", "comete", "oliva",
    "olive", "gengiva", "privi", "privo", "prossimo", "prossima", "pubblicano", "pubblicani",
    "samaritano", "samaritani", "stefano", "giordano", "buono", "buoni", "ebrei", "ebreo",
    "profetesse", "estate", "patate", "polite", "mite",
])

private let participleLexicon: Set<String> = Set<String>([
    "detto", "detta", "detti", "dette", "fatto", "fatta", "fatti", "fatte", "visto", "vista",
    "visti", "viste", "preso", "presa", "presi", "prese", "messo", "messa", "messi", "scelto",
    "scelta", "scelti", "scelte", "scritto", "scritta", "scritti", "scritte", "letto", "letta",
    "letti", "lette", "chiesto", "chiesta", "chiesti", "chieste", "risposto", "risposti",
    "risposte", "morto", "morta", "morti", "nato", "nata", "nati", "nate", "rimasto",
    "rimasta", "rimasti", "rimaste", "aperto", "aperta", "aperti", "aperte", "offerto",
    "offerti", "offerte", "sofferto", "sofferta", "sofferti", "sofferte", "corso", "corsa",
    "corsi", "corse", "perso", "persa", "persi", "perse", "chiuso", "chiusa", "chiusi",
    "chiuse", "deciso", "decisa", "decisi", "decise", "ucciso", "uccisa", "uccisi", "uccise",
    "vinto", "vinta", "vinti", "vinte", "giunto", "giunta", "giunti", "giunte", "spinto",
    "spinta", "spinti", "spinte", "distrutto", "distrutta", "distrutti", "distrutte",
    "condotto", "condotti", "condotte", "posto", "posti", "poste", "composto", "composta",
    "composti", "composte", "rotto", "rotta", "rotti", "rotte", "accolto", "accolta",
    "accolti", "accolte", "colto", "colta", "colti", "colte", "raccolto", "raccolta",
    "raccolti", "raccolte", "volto", "volti", "sepolto", "sepolta", "sepolti", "sepolte",
    "crocifisso", "crocifissa", "crocifissi", "crocifisse", "concepito", "concepita",
    "concepiti", "concepite", "sceso", "scesa", "scesi", "scese", "diviso", "divisa", "divisi",
    "divise", "giaciuto", "apparso", "apparsa", "apparsi", "apparse", "rimesso", "rimessa",
    "rimessi", "rimesse", "dato", "fuggiti", "riuniti", "saliti", "usciti", "partiti",
    "finiti", "risorto", "risorta", "risorti", "risorte", "avvolto", "avvolta", "avvolti",
    "avvolte", "scosso", "scossa", "scossi", "scosse", "disceso", "discesa", "discesi",
    "discese", "effuso", "effusa", "effusi", "promesso", "promessa", "promessi",
])

private let notParticiple: Set<String> = Set<String>([
    "peccato", "peccati", "senato", "prato", "prati", "mercato", "mercati", "avvocato",
    "apostolato", "palato", "fato", "bucato", "ducato", "salute", "virtute", "estate",
    "patate", "spirito", "spiriti", "subito", "partito", "partiti", "vestito", "vestiti",
    "marito", "mariti", "rito", "riti", "sito", "invito", "appetito", "debito", "infinito",
    "gomito", "cubito", "transito", "deposito", "nascita", "unigenito", "paraclito", "sabato",
    "abiti", "abito", "ipocriti", "ipocrita", "saluti", "saluto", "flauto", "esiti", "esito",
    "principati", "principato", "beati", "beato", "beata", "beate", "corsa", "volta", "volte",
    "morte", "posta", "offerta", "risposta", "condotta", "alzati", "àlzati", "goditi",
    "dissoluto", "dissoluta",
])

private let nounParticiples: Set<String> = Set<String>([
    "vista", "viste", "posto", "posti", "morto", "morta", "morti", "fatto", "fatti", "detto",
    "letto", "stato", "stati", "corso", "corsi", "promessa",
])

private let notGerund: Set<String> = Set<String>([
    "quando", "bando", "mando", "rendo", "stendo", "spendo",
])

private let notInfinitive: Set<String> = Set<String>([
    "altare", "altari", "cesare", "mare", "carcere", "carceriere", "lettere", "maniere",
    "opere", "sere", "torre", "polvere", "camere", "febbre", "cifre", "argentiere", "diversi",
    "avversi",
])

private let articles: Set<String> = Set<String>([
    "il", "i", "un", "uno", "una",
])

private let articulated: Set<String> = Set<String>([
    "del", "dello", "della", "dei", "degli", "delle", "al", "allo", "alla", "ai", "agli",
    "alle", "dal", "dallo", "dalla", "dai", "dagli", "dalle", "nel", "nello", "nella", "nei",
    "negli", "nelle", "sul", "sullo", "sulla", "sui", "sugli", "sulle", "col", "coi",
])

private let possessives: Set<String> = Set<String>([
    "mio", "mia", "miei", "mie", "tuo", "tua", "tuoi", "tue", "suo", "sua", "suoi", "sue",
    "nostro", "nostra", "nostri", "nostre", "vostro", "vostra", "vostri", "vostre",
])

private let cliticOrArticle: Set<String> = Set<String>([
    "lo", "la", "le", "gli", "li",
])

private let coordinators: Set<String> = Set<String>([
    "e", "ed", "o", "od", "oppure", "né", "ma", "anzi", "ossia", "ovvero",
])

private let subordinators: Set<String> = Set<String>([
    "che", "chi", "cui", "quando", "qualora", "perché", "poiché", "giacché", "se", "mentre",
    "dove", "come", "quale", "quali", "affinché", "benché", "sebbene", "finché", "appena",
    "purché", "quanto", "quanti", "ove",
])

private let proclitics: Set<String> = Set<String>([
    "mi", "ti", "ci", "vi", "si", "ne", "gli", "lo", "la", "li", "le", "non",
])

private let prepositions: Set<String> = Set<String>([
    "di", "a", "ad", "da", "in", "con", "su", "per", "tra", "fra", "sotto", "sopra", "senza",
    "verso", "presso", "dopo", "prima", "durante", "secondo", "mediante", "contro", "dentro",
    "fuori", "oltre", "entro", "circa", "attraverso", "lungo", "dietro", "davanti", "insieme",
]).union(articulated)

private let timeAdverbs: Set<String> = Set<String>([
    "dopo", "prima", "poi", "oggi", "ieri", "domani", "ora", "allora", "presto", "tardi", "fa",
    "intanto", "frattanto",
])


private let neverNoun: Set<String> = aux.subtracting(["sei", "fosse"])
private let determiners: Set<String> = articles.union(articulated).union(possessives)

// ── elision and clitics ──────────────────────────────────────────────────────

// JS: /^([a-zà-ÿ]{1,4})['’](.+)$/ on the lowercased word.
private func isElisionPrefixChar(_ c: Character) -> Bool {
    guard c.unicodeScalars.count == 1, let v = c.unicodeScalars.first?.value else { return false }
    return (0x61...0x7A).contains(v) || (0xE0...0xFF).contains(v)
}

private func elisionSplit(_ word: String) -> String? {
    let chars = Array(word.lowercased())
    guard let apo = chars.firstIndex(where: { $0 == "'" || $0 == "’" }),
          (1...4).contains(apo),
          chars[..<apo].allSatisfy(isElisionPrefixChar),
          apo + 1 < chars.count
    else { return nil }
    return String(chars[(apo + 1)...])
}

public func stripElision(_ word: String) -> String {
    elisionSplit(word) ?? word.lowercased()
}

public func hasElision(_ word: String) -> Bool {
    elisionSplit(word) != nil
}

// JS: /(?:gli|lo|la|li|le|ne|mi|ti|ci|vi|si)$/ — "gli" is tried first.
private let twoLetterEnclitics = ["lo", "la", "li", "le", "ne", "mi", "ti", "ci", "vi", "si"]

private func encliticLength(_ w: String) -> Int? {
    if w.hasSuffix("gli") { return 3 }
    return twoLetterEnclitics.contains(where: { w.hasSuffix($0) }) ? 2 : nil
}

public func stripClitics(_ word: String) -> String {
    var w = stripElision(word)
    for _ in 0..<2 {
        guard let n = encliticLength(w) else { break }
        let stem = String(w.dropLast(n))
        if stem.count < 4 { break }
        w = stem
    }
    return w
}

private func endsWith(_ w: String, _ suffixes: [String]) -> Bool {
    suffixes.contains(where: { w.hasSuffix($0) })
}

// ── auxiliaries ──────────────────────────────────────────────────────────────

public func isAuxiliary(_ word: String) -> Bool {
    let w = stripElision(word)
    return aux.contains(w) || nonfiniteAux.contains(w) || nonfiniteAux.contains(stripClitics(w))
}

// ── finite verbs ─────────────────────────────────────────────────────────────

private let imperfettoEndings: [String] = ["av", "ev", "iv"].flatMap { stem in
    ["o", "i", "a", "amo", "ate", "ano"].map { stem + $0 }
}
private let futureEndings: [String] = [
    "ò", "ai", "à", "emo", "ete", "anno", "ei", "esti", "ebbe", "emmo", "este", "ebbero",
].map { "r" + $0 }

// JS FINITE_SUFFIXES, as [suffixes, minimum length].
private let finiteSuffixes: [([String], Int)] = [
    (imperfettoEndings, 5),                          // imperfetto
    (futureEndings, 5),                              // futuro / condizionale
    (["ò", "ì"], 3),                                 // passato remoto 3sg
    (["ai"], 5),                                     // passato remoto 1sg
    (["arono", "erono", "irono", "ettero"], 6),      // passato remoto 3pl
    (["ssero", "ssimo"], 6),                         // congiuntivo / pass. rem. pl
    (["asse", "esse", "isse"], 5),                   // congiuntivo imperfetto sg
    (["iamo"], 5),                                   // 1a plurale
    (["ate", "ite", "ete"], 5),                      // 2a plurale / imperativo
    (["ano", "ono"], 5),                             // 3a plurale presente
]

public func isFiniteVerb(_ word: String) -> Bool {
    let w = stripElision(word)
    if w.isEmpty || notFinite.contains(w) { return false }
    if finiteLexicon.contains(w) { return true }
    if finiteSuffixes.contains(where: { w.count >= $0.1 && endsWith(w, $0.0) }) { return true }
    // An imperative that swallowed its pronoun ("lodàtelo"): only the lexicon
    // and the imperative endings may apply to the stripped stem.
    let stem = stripClitics(w)
    if stem == w || notFinite.contains(stem) { return false }
    return finiteLexicon.contains(stem)
        || (stem.count >= 5 && endsWith(stem, ["iamo", "ate", "ite", "ete"]))
}

// ── participles, gerunds, infinitives ────────────────────────────────────────

// JS: /(?:(?:at|ut)[oai]|it[oa])$/
private let participleEndings = ["ato", "ati", "ata", "uto", "uti", "uta", "ito", "ita"]

public func isParticiple(_ word: String) -> Bool {
    let w = stripElision(word)
    if w.isEmpty || hasElision(word) || notParticiple.contains(w) { return false }
    if participleLexicon.contains(w) { return true }
    return w.count >= 5 && endsWith(w, participleEndings)
}

public func isGerund(_ word: String) -> Bool {
    let w = stripClitics(stripElision(word))
    return w.count >= 6 && endsWith(w, ["ando", "endo"]) && !notGerund.contains(w)
}

public func isInfinitive(_ word: String) -> Bool {
    let w = stripElision(word)
    if hasElision(word) { return false }
    if w.count < 4 || notInfinitive.contains(w) { return false }
    return endsWith(w, ["are", "ere", "ire", "arsi", "ersi", "irsi"])
}

public func isDeterminer(_ word: String) -> Bool {
    determiners.contains(stripElision(word))
}

// ── analysis ─────────────────────────────────────────────────────────────────

private let auxLookback = 2
private let sentenceStops: Set<Character> = [".", ";", ":", "!", "?", "…", "»", "«", "\""]
private let feminineParticipleEndings = ["ate", "ute", "ite"]

private struct Segment {
    let start: Int
    let end: Int
    let closedLeft: Bool
    let closedRight: Bool
    var wordIndices: [Int] = []
    var head: String = ""
}

/// Analyze one sentence — see `analyze()` in clauseSkeleton.js.
public func analyzeClauses(_ text: String) -> ClauseAnalysis {
    var tokens = tokenize(text).map {
        SkeletonToken(text: $0.text, isWord: $0.isWord, role: .plain, dim: false)
    }
    let wordIdx = tokens.indices.filter { tokens[$0].isWord }

    // The word before word n, only when nothing but whitespace separates them.
    func prevWord(_ n: Int) -> String {
        guard n > 0 else { return "" }
        let gap = tokens[(wordIdx[n - 1] + 1)..<wordIdx[n]].map(\.text).joined()
        return gap.allSatisfy(\.isWhitespace) ? stripElision(tokens[wordIdx[n - 1]].text) : ""
    }
    // A possessive only determines what follows when it is prenominal.
    func afterDeterminerAt(_ n: Int) -> Bool {
        let prev = prevWord(n)
        guard determiners.contains(prev) else { return false }
        guard possessives.contains(prev) else { return true }
        let before = prevWord(n - 1)
        return before.isEmpty || determiners.contains(before)
            || prepositions.contains(before) || cliticOrArticle.contains(before)
    }
    func leansOnAux(_ n: Int) -> Bool {
        wordIdx[max(0, n - auxLookback)..<n].contains { isAuxiliary(tokens[$0].text) }
    }

    // Pass 1 — conjugated verbs, in context.
    for (n, i) in wordIdx.enumerated() {
        let prev = prevWord(n)
        let afterDeterminer = afterDeterminerAt(n)
        let afterArticleOrClitic = afterDeterminer || cliticOrArticle.contains(prev)
        let w = stripElision(tokens[i].text)

        guard isFiniteVerb(tokens[i].text) else { continue }
        if !neverNoun.contains(w) {
            if afterDeterminer { continue }
            if nounHomographVerbs.contains(w), afterArticleOrClitic || prenominal.contains(prev) { continue }
        }
        if isParticiple(tokens[i].text), leansOnAux(n) { continue }
        tokens[i].role = .finite
    }

    // Pass 1b — participles: compound after an auxiliary, bare otherwise.
    for (n, i) in wordIdx.enumerated() {
        if tokens[i].role == .finite { continue }
        let w = stripElision(tokens[i].text)
        let prev = prevWord(n)
        if leansOnAux(n) {
            if isParticiple(tokens[i].text)
                || (w.count >= 4 && endsWith(w, feminineParticipleEndings) && !hasElision(tokens[i].text))
                || (peccatoLike.contains(w) && avere.contains(prev)) {
                tokens[i].role = .compound
            }
            continue
        }
        guard isParticiple(tokens[i].text) else { continue }
        if afterDeterminerAt(n) || cliticOrArticle.contains(prev) || prenominal.contains(prev) { continue }
        if nounParticiples.contains(w) { continue }
        tokens[i].role = .participle
    }

    // Pass 2 — asides.
    var segments: [Segment] = []
    var start = 0
    var leftComma = false
    for (i, t) in tokens.enumerated() where !t.isWord {
        let stop = t.text.contains(where: { sentenceStops.contains($0) })
        let comma = t.text.contains(",")
        if !stop && !comma { continue }
        segments.append(Segment(start: start, end: i, closedLeft: leftComma, closedRight: !stop && comma))
        start = i + 1
        leftComma = !stop && comma
    }
    segments.append(Segment(start: start, end: tokens.count, closedLeft: leftComma, closedRight: false))

    for s in segments.indices {
        let seg = segments[s]
        let words = (seg.start..<seg.end).filter { tokens[$0].isWord }
        segments[s].wordIndices = words
        segments[s].head = words.first.map { stripElision(tokens[$0].text) } ?? ""
        // A lone feminine-plural participle between commas ("ma, entrate,").
        if seg.closedLeft, seg.closedRight, words.count == 1 {
            let only = words[0]
            if tokens[only].role == .finite, endsWith(stripElision(tokens[only].text), feminineParticipleEndings) {
                tokens[only].role = .participle
            }
        }
    }

    var hasParenthetical = false
    for s in segments.indices {
        let seg = segments[s]
        guard seg.closedLeft, seg.closedRight else { continue }
        let prev: Segment? = s > 0 ? segments[s - 1] : nil
        let next: Segment? = s + 1 < segments.count ? segments[s + 1] : nil
        guard isAsideSegment(seg, prev: prev, next: next, tokens: tokens) else { continue }
        hasParenthetical = true
        for j in seg.start..<seg.end { tokens[j].dim = true }
    }

    return ClauseAnalysis(
        tokens: tokens,
        finiteCount: tokens.filter { $0.role == .finite }.count,
        hasParenthetical: hasParenthetical
    )
}

private func isAsideSegment(_ seg: Segment, prev: Segment?, next: Segment?, tokens: [SkeletonToken]) -> Bool {
    let words = seg.wordIndices.map { tokens[$0] }
    if words.isEmpty { return false }
    if words.contains(where: { $0.role == .finite || $0.role == .compound }) { return false }
    let head = seg.head
    if coordinators.contains(head) || subordinators.contains(head) || proclitics.contains(head) { return false }
    if words.contains(where: { isInfinitive($0.text) }) { return false }

    // An implicit clause — gerund or bare participle — is an aside at any length.
    if words.contains(where: { $0.role == .participle || isGerund($0.text) }) { return true }

    if words.count > 6 { return false }
    if words.contains(where: { subordinators.contains(stripElision($0.text)) }) { return false }

    if prepositions.contains(head) {
        if prev?.head == head || next?.head == head { return false }
        if words.contains(where: { coordinators.contains(stripElision($0.text)) }) { return false }
        return true
    }

    if articles.contains(head) && words.count < 3 { return false }
    if words.count > 1 {
        guard let prev, let beforeIdx = prev.wordIndices.last else { return false }
        let tail = stripElision(tokens[beforeIdx].text)
        if coordinators.contains(tail) || prepositions.contains(tail) || timeAdverbs.contains(tail) { return false }
    }
    return true
}
